dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 5.3
  
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: travis_retry composer install

script:
  - ./vendor/bin/phpunit test/*MockTest.php
